name: dalesys
favicon: null
layout_spectrum: 0.25236
typography_spectrum: 1
title: DALESYS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefbf4'
    - '#d5dee5'
    - '#3a3f45'
    - '#adadad'
    - '#786e67'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
