name: Test
favicon: null
layout_spectrum: 0.50978
typography_spectrum: 0.93257
title: Dalesys
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02101b'
    - '#fcfcfc'
    - '#1d65bf'
    - '#ab96b9'
    - '#fc5447'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
