name: Test
favicon: null
layout_spectrum: 0.50089
typography_spectrum: 1
title: DALESYS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000403'
    - '#023224'
    - '#034b35'
    - '#02655e'
    - '#037c6d'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
